---
- name: VM Installer
  hosts: webservers
  become: true
  tasks:

  - name:  Install docker.io  (state=present is optional)
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name:  Install python3-pip
    apt:
      name: python3-pip
      state: present

  - name:  Install Docker w/ pip
    pip:
      name: docker
      state: present

  - name:  Install cyberxsecurity/dvwa
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80
